/**
 * DO NOT EDIT! This file has been generated by Ant
 **/

package org.mbs3.ant.tests;

public class SampleClass {
	public static final String Maybe = "Maybe";
	public static final String Goodbye = "Goodbye";
	public static final String Hello = "Hello";
}
